Repository neetozone/neeto-ui, pull requests merged in 2021-11, with the labels that each got.

#590 Added Footer links to Sidebar
  example/src/Playground.js
  example/src/constants.js
  lib/components/layouts/Sidebar.js
  package.json
  stories/Sidebar.stories.jsx
  yarn.lock
Labels: makepr

#597 Update Table component
  example/src/Pages/Table.js
  example/src/Pages/constants.js
  example/src/constants.js
  lib/components/Table.js
  lib/components/index.js
  lib/styles/components/_checkbox.scss
  lib/styles/components/_table.scss
  lib/styles/index.scss
  lib/styles/venders/_ant-animations.scss
  lib/styles/venders/_ant-spin.scss
  lib/styles/venders/_antd-date-picker.scss
  lib/styles/venders/_antd-pagination.scss
  lib/styles/venders/_antd-select.scss
  lib/styles/venders/_antd-table.scss
  stories/Table.stories.jsx
  stories/TableDocs.mdx
  stories/constants.js
Labels: makepr

#622 Table Improvements
  example/src/Pages/Table.js
  example/src/Pages/constants.js
  lib/components/Table.js
  lib/styles/components/_table.scss
  stories/Components/Table.stories.jsx
  stories/Components/TableDocs.mdx
Labels: makepr

#635 Automated release creation process
  .github/release-drafter.yml
  .github/workflows/publish.yml
Labels: release

#638 Fix git action
  .github/workflows/publish.yml
Labels: release

#665 Separate css in bundle file
  .storybook/main.js
  lib/components/layouts/index.js
  package.json
  tailwind.config.js
  v2/formik.js.LICENSE.txt
  v2/index.css
  v2/index.js.LICENSE.txt
  v2/layouts.js.LICENSE.txt
  webpack.config.js
  yarn.lock
Labels: major-version-change, release
