Repository neetozone/neeto-ui, pull requests merged in 2022-09, with the labels that each got.

#1300 Fix tag styles
  .github/workflows/publish.yml
  index.d.ts
  lib/components/Tag.js
  lib/styles/components/_tag.scss
  stories/Components/Tag.stories.jsx
Labels: minor

#1299 Fixed issue with custom target in dropdown
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: patch

#1302 Revert "Fixed issue with custom target in dropdown"
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: skip-ci

#1303 Fixed custom target issue in dropdown
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: patch

#1304 Revert "Fixed custom target issue in dropdown"
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: skip-ci

#1305 Fixed custom target issue in dropdown
  .github/workflows/publish.yml
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: patch

#1307 Fixed custom target issue in dropdown
  .github/workflows/publish.yml
  lib/components/Dropdown/index.js
  lib/styles/components/_table.scss
  stories/Components/Dropdown.stories.jsx
  stories/Components/Table.stories.jsx
Labels: patch

#1310 Updated migration doc
  stories/Introduction/GettingStarted.stories.mdx
  stories/Migration-Guide/v3tov4.stories.mdx
Labels: skip-ci

#1311 Added story to reference older versions
  .storybook/preview.js
  stories/Introduction/OlderVersions.stories.mdx
Labels: skip-ci

#1314 UI fixes
  .storybook/main.js
  .storybook/neetoTheme.js
  .storybook/preview-head.html
  .storybook/preview.js
  lib/styles/components/_date-time-picker.scss
  package.json
  stories/Components/Table.stories.jsx
  stories/Components/TableStoriesDocs/TableDocs.mdx
  stories/Foundation/ColorStory.jsx
  yarn.lock
Labels: patch

#1317 Allowed `hideOnSinglePage` override in `Table`
  example/src/Pages/Layouts.js
  lib/components/Table.js
  stories/Components/Table.stories.jsx
  stories/Layouts.stories.jsx
  stories/Layouts/MenuBar.stories.jsx
Labels: patch

#1322 Added light theme as default
  .storybook/preview.js
Labels: skip-ci

#1319 Added allowance for data-cy props
  index.d.ts
Labels: patch

#1323 Updated table docs
  lib/components/Table.js
  stories/Components/Table.stories.jsx
  stories/constants.js
Labels: patch

#1324 Revert "Updated table docs"
  lib/components/Table.js
  stories/Components/Table.stories.jsx
  stories/constants.js
Labels: skip-ci

#1325 Updated table docs
  lib/components/Table.js
  stories/Components/Table.stories.jsx
  stories/constants.js
Labels: patch

#1329 Change app switcher links to admin page of applications
  lib/constants/clientApps.js
Labels: patch

#1340 Changes variables in snakecase to camelcase
  stories/Components/Table.stories.jsx
  stories/Layouts.stories.jsx
Labels: skip-ci

#1344 Fixed warning with tags and datepicker component
  lib/components/DatePicker.js
  lib/components/Tag.js
  lib/constants/clientApps.js
Labels: patch
