Repository neetozone/neeto-ui, pull requests merged in 2022-04, with the labels that each got.

#1046 Fix Typography in Alert
  CHANGELOG.md
  lib/components/Alert.js
  lib/components/Dropdown.js
Labels: release

#1044 update docs for table component
  stories/Components/Table.stories.jsx
  stories/Components/TableDocs.mdx
  stories/constants.js
Labels: skip-ci

#1048 Add workflow to enforce versioning labels
  .github/workflows/enforce-label.yml
  .github/workflows/publish.yml
Labels: skip-ci

#1057 Added data-cy to alert component
  .github/workflows/enforce-label.yml
  .github/workflows/labeler.yml
  CHANGELOG.md
  lib/components/Alert.js
Labels: patch

#1059 Release action modified
  .github/workflows/publish.yml
Labels: skip-ci

#1060 Trigger release action
  tests/Input.test.js
Labels: patch

#1063 Added hideOnScroll prop to tooltip
  CHANGELOG.md
  lib/components/Tooltip.js
  lib/styles/components/_dropdown.scss
  stories/Components/Dropdown.stories.jsx
  stories/Overlays/Tooltip.stories.jsx
Labels: patch

#1065 Enforce-label workflow trigger updated
  .github/workflows/enforce-label.yml
  .github/workflows/labeler.yml
Labels: skip-ci

#1062 add test for container
  tests/Container.test.js
Labels: skip-ci

#1055 add test for scrollable
  tests/Scrollable.test.js
Labels: skip-ci

#1061 Added tests for formik Input
  babel.config.js
  package.json
  tests/formik/Input.test.js
  yarn.lock
Labels: skip-ci

#979 Added active state to NavLink in sidebar
  CHANGELOG.md
  lib/components/layouts/Sidebar/Footer/FooterLink/Link.js
Labels: patch

#1064 added tests for the Sidebar component
  tests/Sidebar.test.js
Labels: skip-ci

#1073 added tests for Menubar
  tests/Menubar.test.js
  tests/Sidebar.test.js
Labels: skip-ci

#1077 Data missing data-cy for email input
  lib/components/EmailInput.js
  lib/components/Input.js
Labels: skip-ci

#1066 Revert Formik data on clicking BlockNavigation continue
  CHANGELOG.md
  lib/components/formik/BlockNavigation.js
Labels: patch

#1075 Fixed table story classname
  stories/Components/Table.stories.jsx
Labels: skip-ci

#1079 Dropdown docs updated
  example/src/Pages/Dropdown.js
  lib/components/Dropdown.js
  stories/Components/Dropdown.stories.jsx
Labels: skip-ci

#1081 Added id for Select input and `for` attribute for Select label.
  lib/components/Select.js
Labels: skip-ci

#1084 Updated react, react-dom and react-router-dom
  CHANGELOG.md
  package.json
  yarn.lock
Labels: patch

#1091 Adds Tests for formik checkbox
  tests/formik/checkbox.test.js
Labels: skip-ci

#1094 Added tests for formik/TextArea component
  lib/components/formik/Textarea.js
  tests/formik/Textarea.test.js
Labels: skip-ci

#1092 Adds tests for Formik emailInput
  tests/formik/EmailInput.test.js
Labels: skip-ci

#1093 Added tests for formik/Switch
  tests/formik/Switch.test.js
Labels: skip-ci

#1089 Add tests for formik select
  tests/formik/Select.test.js
Labels: skip-ci

#1085 Added select control for icon prop
  stories/Components/Button.stories.jsx
  stories/Components/Dropdown.stories.jsx
  stories/Components/Tag.stories.jsx
  stories/constants.js
Labels: skip-ci

#1090 Adds Formik Radio button tests
  tests/formik/Radio.test.js
Labels: skip-ci

#1100 Updated Toggle Switch UI
  lib/components/Switch.js
  lib/styles/components/_switch.scss
  tests/AppSwitcher.test.js
Labels: patch

#1106 Added tests for formik/ActionBlock
  tests/formik/ActionBlock.test.js
Labels: skip-ci

#1108 Added tests for formik/BlockNavigation
  tests/formik/BlockNavigation.test.js
Labels: skip-ci

#1110 ActionDropdown `buttonProps` fix
  CHANGELOG.md
  lib/components/ActionDropdown.js
Labels: patch

#1112 Fixed version in readme
  README.md
Labels: skip-ci

#1107 Removed unnecessary scrollbar from Table
  CHANGELOG.md
  lib/styles/components/_table.scss
Labels: patch

#1116 Fixed pre commit hook
  package.json
  yarn.lock
Labels: skip-ci

#1101 Changed EmailInput to accept more generic inputs.
  CHANGELOG.md
  lib/components/EmailInput.js
  lib/constants/EmailInput.js
  tests/EmailInput.test.js
  tests/formik/EmailInput.test.js
Labels: patch

#1118 Ignore `example` folder from test coverage
  jest.config.js
Labels: skip-ci

#1120 Improved loading state in ActionBlock
  CHANGELOG.md
  lib/components/formik/ActionBlock.js
Labels: patch
