Repository neetozone/neeto-ui, pull requests merged in 2022-05, with the labels that each got.

#1117 Tags molecule component added
  .eslintrc.js
  .storybook/preview.js
  CHANGELOG.md
  example/src/constants.js
  lib/Molecules/Tags/index.js
  stories/Molecules/Tags.stories.jsx
  tests/Molecules/Tags.test.js
Labels: patch

#1122 Fixed input autoFocus not working inside Dropdown
  CHANGELOG.md
  example/src/Pages/Dropdown.js
  lib/components/Dropdown.js
  package.json
  tests/ColorPicker.test.js
  tests/Dropdown.test.js
  yarn.lock
Labels: patch

#1124 Fixed search not working with Select creatable
  CHANGELOG.md
  lib/Molecules/Tags/index.js
  lib/components/Select.js
  stories/Components/Select.stories.jsx
  tests/Select.test.js
Labels: patch

#1131 Test Branch protection
  stories/Components/Input.stories.jsx
Labels: patch

#1132 Github secret token for push updated in publish action
  .github/workflows/publish.yml
Labels: patch

#1129 Added prefix and suffix props to EmailInput
  CHANGELOG.md
  lib/components/EmailInput.js
  lib/styles/components/_email-input.scss
  stories/Components/EmailInput.stories.jsx
  stories/constants.js
Labels: patch

#1135 PR template added
  .github/pull_request_template.md
Labels: skip-ci

#1138 Fixed Import for molecules components
  CHANGELOG.md
  lib/Molecules/index.js
  stories/Molecules/Tags.stories.jsx
  webpack.config.js
Labels: patch

#1139 Added step to extract changelog content and update version
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: skip-ci

#1143 Revert "Fixed type error issue with toastr"
  lib/components/Toastr/index.js
Labels: skip-ci

#1144 Minor fix to github action
  .github/workflows/publish.yml
Labels: patch

#1150 PR template updated
  .github/pull_request_template.md
  .github/workflows/publish.yml
Labels: skip-ci

#1145 Replaced webpack with rollup bundler
  .gitignore
  .npmignore
  jsconfig.json
  lib/molecules/Tags/index.js
  lib/molecules/index.js
  molecules.js
  molecules.js.LICENSE.txt
  package.json
  rollup.config.js
  stories/Molecules/Tags.stories.jsx
  tests/molecules/Tags.test.js
  webpack.config.js
  yarn.lock
Labels: minor

#1153 Fixed spacing in tags molecule
  lib/molecules/Tags/index.js
Labels: patch
