Repository neetozone/neeto-ui, pull requests merged in 2024-01, with the labels that each got.

#2033 Ability to see info about a table column
  index.d.ts
  src/components/Dropdown/MenuItem/MenuItemButton.jsx
  src/components/Popover/index.jsx
  src/components/Table/HeaderCell.jsx
  src/components/Table/components/HeaderCell/CellContent.jsx
  src/components/Table/components/HeaderCell/HeaderCell.jsx
  src/components/Table/components/HeaderCell/HeaderCellMenu.jsx
  src/components/Table/components/HeaderCell/ResizableHeaderCell.jsx
  src/components/Table/components/HeaderCell/index.jsx
  src/components/Table/components/SortIcon.jsx
  src/components/Table/constants.js
  src/components/Table/hooks/useColumns.js
  src/components/Table/hooks/useResizableColumns.js
  src/components/Table/index.jsx
  src/components/Table/utils.js
  stories/Components/Table.stories.jsx
  tests/Table.test.jsx
Labels: minor

#2056 Added missing props to date-time-picker component
  index.d.ts
  src/components/DateTimePicker/index.jsx
  src/components/TimePickerInput/index.jsx
  tests/DatePicker.test.jsx
  tests/TimePickerInput.test.jsx
Labels: patch

#2061 Added support for disabling the create option for MultiEmailInput
  index.d.ts
  src/components/MultiEmailInput/index.jsx
  tests/MultiEmailInput.test.jsx
Labels: patch

#2064 Updated antd version to the correct version in the readme
  README.md
Labels: documentation

#2063 Fixed column info popover style
  src/components/Table/components/HeaderCell/HeaderCellMenu.jsx
  src/styles/components/_dropdown.scss
  src/styles/components/_popover.scss
Labels: dont-merge, patch

#2070 More actions on table header
  index.d.ts
  src/components/Table/components/HeaderCell/CellContent.jsx
  src/components/Table/components/HeaderCell/HeaderCellMenu.jsx
  src/components/Table/hooks/useColumns.js
  src/components/Table/hooks/useResizableColumns.js
  src/components/Table/index.jsx
  stories/Components/Table.stories.jsx
  stories/Components/TableStoriesDocs/MoreActionsOnHeaderDocs.mdx
  stories/constants.jsx
  tests/Table.test.jsx
Labels: minor

#2073 Fix table column width and button shrinking issue in table cell
  src/styles/components/_table-overrides.scss
Labels: patch
