Repository neetozone/neeto-ui, pull requests merged in 2024-07, with the labels that each got.

#2237 Updated the scrollbar color
  src/components/Table/index.jsx
Labels: patch

#2238 Improved DatePicker and TimePicker components
  src/components/DatePicker/index.jsx
  src/components/TimePicker/index.jsx
  tests/DatePicker.test.jsx
  tests/TimePicker.test.jsx
  types/DatePicker.d.ts
  types/TimePicker.d.ts
Labels: patch

#2246 Disabled mask format in DatePicker and TimePicker
  src/components/DatePicker/index.jsx
  src/components/TimePicker/index.jsx
  tests/DatePicker.test.jsx
  tests/TimePicker.test.jsx
Labels: patch

#2244 Updated framer-motion to 11.2.14
  package.json
  yarn.lock
Labels: patch

#2252 Added support for displaying tooltips for disabled buttons in NoData component
  src/components/NoData/index.jsx
  tests/NoData.test.jsx
  types/NoData.d.ts
Labels: patch

#2249 Added a new TranslationProvider for initializing translations for external use of NeetoUI
  .storybook/main.js
  .storybook/preview.js
  jest.config.js
  package.json
  src/components/DatePicker/Today.jsx
  src/components/Table/components/HeaderCell/HeaderCellMenu.jsx
  src/components/TimePicker/index.jsx
  src/components/TranslationProvider/i18n.js
  src/components/TranslationProvider/index.jsx
  src/components/TreeSelect.jsx
  src/components/index.js
  src/formik/ActionBlock.jsx
  src/formik/BlockNavigation.jsx
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/index.js
  src/translations/nl.json
  src/translations/pl.json
  src/translations/pt.json
  src/utils/index.js
  stories/Internationalization/TranslationProvider.stories.mdx
  types/TranslationProvider.d.ts
Labels: minor

#2262 Removed TimePickerInput and DateTimePicker components
  index.d.ts
  src/components/DateTimePicker/index.jsx
  src/components/DateTimePicker/utils.js
  src/components/TimePickerInput/HoverIcon.jsx
  src/components/TimePickerInput/index.jsx
  src/components/TimePickerInput/useRefState.js
  src/components/TimePickerInput/utils.js
  src/components/index.js
  stories/Components/DateTimePicker.stories.jsx
  stories/Components/DateTimePickerStoriesDocs/DateTimePickerCSSCustomization.mdx
  stories/Components/DateTimePickerStoriesDocs/DateTimePickerDocs.mdx
  stories/Components/TimePickerInput.stories.jsx
  stories/Components/TimePickerInputStoriesDocs/TimePickerInputCSSCustomization.mdx
  stories/Components/TimePickerInputStoriesDocs/TimePickerInputDocs.mdx
  tests/DateTimePicker.test.jsx
  tests/TimePickerInput.test.jsx
  types/DateTimePicker.d.ts
  types/TimePickerInput.d.ts
Labels: major

#2265 Added internationalization support for antd component
  src/components/DatePicker/Provider.jsx
  src/components/Slider/index.jsx
  src/components/Table/index.jsx
  src/components/TimePicker/index.jsx
  src/components/Tree/index.jsx
  src/components/TreeSelect.jsx
  src/components/constants.js
Labels: patch

#2255 Updates all formik components in neetoui to use status field to server errors.
  src/formik/Checkbox.jsx
  src/formik/Input.jsx
  src/formik/MultiEmailInput.jsx
  src/formik/Radio.jsx
  src/formik/Select.jsx
  src/formik/Slider.jsx
  src/formik/Switch.jsx
  src/formik/Textarea.jsx
  src/formik/TreeSelect.jsx
  tests/formik/EmailInput.test.jsx
  tests/formik/Input.test.jsx
  tests/formik/Radio.test.jsx
  tests/formik/Select.test.jsx
  tests/formik/Slider.test.jsx
  tests/formik/Switch.test.jsx
  tests/formik/Textarea.test.jsx
  tests/formik/TreeSelect.test.jsx
  tests/formik/checkbox.test.jsx
Labels: minor

#2270 Fixes incorrect usage of dissoc in formik fields.
  src/formik/Checkbox.jsx
  src/formik/Input.jsx
  src/formik/MultiEmailInput.jsx
  src/formik/Radio.jsx
  src/formik/Select.jsx
  src/formik/Slider.jsx
  src/formik/Switch.jsx
  src/formik/Textarea.jsx
  src/formik/TreeSelect.jsx
Labels: patch

#2268 Prevents form submission when the server errors are set.
  src/formik/Form/FormWrapper.jsx
  src/formik/Form/ScrollToErrorField/index.js
  src/formik/Form/ScrollToErrorField/utils.js
  src/formik/Form/index.jsx
Labels: patch

#2271 Update Spinner style
  src/atoms/Spinner.jsx
  src/atoms/index.js
  src/components/Button.jsx
  src/components/Spinner.jsx
  src/styles/components/_button.scss
  src/styles/components/_spinner.scss
  stories/Components/SpinnerStoriesDocs/SpinnerCSSCustomization.mdx
Labels: patch

#2273 Update the default font family to Inter on Windows
  .storybook/neetoTheme.js
  .storybook/preview-head.html
  src/styles/abstracts/_variables.scss
  src/styles/base/_base.scss
  src/styles/components/_table-overrides.scss
  src/styles/components/_toast.scss
  stories/Introduction/Welcome.stories.mdx
Labels: patch

#2276 Added documentation on handling server side validation errors in the form.
  stories/Formik/Form.stories.jsx
  stories/Formik/ServerValidationErrors.mdx
Labels: patch

#2242 Persist scroll position of the table during navigation
  .eslintrc.js
  package.json
  src/components/Table/hooks/useRestoreScrollPosition.js
  src/components/Table/index.jsx
  src/hooks/index.js
  src/hooks/useFuncDebounce.js
  yarn.lock
Labels: minor

#2277 Added optional chaining to prevent scrollTo being accessed on a null value
  src/components/Table/hooks/useRestoreScrollPosition.js
Labels: patch
