Repository neetozone/neeto-ui, pull requests merged in 2024-03, with the labels that each got.

#2106 Table: update sortedInfo from queryParams
  src/components/Table/hooks/useTableSort.js
  src/components/Table/index.jsx
Labels: patch

#2109 TimpickerInput: Fix firefox ui issue
  src/styles/components/_time-picker-input.scss
Labels: patch

#2112 Select: fix `strategy="fixed"` not scrolling to selected
  src/components/Select.jsx
  stories/Components/Select.stories.jsx
Labels: patch, 0.25D

#2113 Added support for resize, suffix, prefix and sizing for textarea
  src/components/Textarea.jsx
  src/styles/components/_input.scss
  stories/Components/Textarea.stories.jsx
Labels: patch

#2115 Additional dropdown triggers
  index.d.ts
  src/components/Dropdown/index.jsx
  tests/Dropdown.test.jsx
Labels: patch

#2117 Added data attribute to target triple dots in table header
  src/components/Table/components/HeaderCell/HeaderCellMenu.jsx
Labels: patch

#2122 Added support for overriding props of the dropdown in the ColorPicker
  index.d.ts
  src/components/ColorPicker/index.jsx
Labels: patch

#2124 Navigating through pages in table will not reset selected rows by default
  README.md
  src/components/Table/index.jsx
Labels: patch

#2128 Removed auto update PRs workflow
  .github/workflows/auto_update_prs_with_latest_master.yml
Labels: mergepr

#2121 DateTimePicker: Add min and max date time.
  index.d.ts
  jest-setup.js
  package.json
  src/components/DatePicker.jsx
  src/components/DateTimePicker/index.jsx
  src/components/DateTimePicker/utils.js
  stories/Components/DateTimePicker.stories.jsx
  tests/DatePicker.test.jsx
  tests/DateTimePicker.test.jsx
  yarn.lock
Labels: minor

#2127 Added functionality for selecting all rows in multi-page table
  src/components/Table/components/SelectAllRowsCallout.jsx
  src/components/Table/index.jsx
  src/components/Table/utils.js
  stories/Components/Table.stories.jsx
  tests/Table.test.jsx
Labels: minor

#2138 Added `isSubmitting` prop for `ActionBlock` component
  formik.d.ts
  src/components/formik/ActionBlock.jsx
  tests/formik/ActionBlock.test.jsx
Labels: patch

#2136 Fix alignment issue with Label
  src/components/Label.jsx
  src/styles/components/_input.scss
Labels: dont-merge

#2143 Added styles for ActionBlock component
  src/styles/components/_action-block.scss
  src/styles/index.scss
Labels: patch

#2145 DatePicker: fix unable to switch to different month or year
  src/components/DatePicker.jsx
Labels: patch

#2141 Table: Fixed sort state persisting when the query param is removed
  src/components/Table/hooks/useTableSort.js
Labels: patch

#2152 Revert "Fix alignment issue with Label"
  src/components/Label.jsx
  src/styles/components/_input.scss
Labels: patch

#2151 Fixed not able to clear selections when bulk selected all row is true
  src/components/Table/index.jsx
Labels: patch
