Repository neetozone/neeto-ui, pull requests merged in 2024-05, with the labels that each got.

#2179 Return toastId when calling toastr
  src/components/Toastr/index.jsx
  tests/Toastr.test.jsx
  types/Toastr.d.ts
Labels: patch

#2181 Fixed toastId returning undefined when using Toastr.error
  src/components/Toastr/index.jsx
  tests/Toastr.test.jsx
  types/Toastr.d.ts
Labels: patch

#2183 Added onBlur handler for textarea to trim leading and trailing spaces
  src/components/Textarea.jsx
  tests/Textarea.test.jsx
Labels: patch

#2182 Added ability to reset timestamp value to null using value prop
  src/components/DateTimePicker/index.jsx
  src/components/TimePickerInput/index.jsx
Labels: patch

#2189 Updated onChange handler types of ColorPicker
  types/ColorPicker.d.ts
Labels: patch

#2194 Moved loader position to center
  src/components/Button.jsx
  src/styles/components/_button.scss
Labels: dont-merge, patch

#2191 Updated the modal footer UI
  src/components/Alert.jsx
  src/formik/ActionBlock.jsx
  src/styles/components/_modal.scss
  stories/Overlays/Modal.stories.jsx
  types/formik/ActionBlock.d.ts
Labels: patch

#2199 Added `ProgressBar` component
  .storybook/preview.js
  index.d.ts
  src/components/ProgressBar.jsx
  src/components/index.js
  src/styles/components/_progress-bar.scss
  src/styles/index.scss
  stories/Components/ProgressBar.stories.jsx
  stories/Components/ProgressBarDocs/ProgressBarCSSCustomization.mdx
  stories/Components/ProgressBarDocs/ProgressBarDocs.mdx
  tests/ProgressBar.test.jsx
  types/ProgressBar.d.ts
Labels: minor

#2205 Fixes avatar background color inconsistency.
  src/components/Avatar.jsx
Labels: patch

#2160 Move dependencies to peerDependencies
  CHANGELOG.md
  README.md
  package.json
Labels: minor

#2206 Removed framer-motion and react-select from peer dependencies
  package.json
Labels: patch

#2209 Repositions color palette to top
  src/components/ColorPicker/index.jsx
  src/styles/components/_color-picker.scss
Labels: patch

#2211 Enhance the mobile responsiveness of the Stepper component
  src/styles/components/_stepper.scss
Labels: patch

#2212 Improved Avatar status UI
  src/styles/components/_avatar.scss
Labels: patch
